PTM:
  - file: data/WT_vs_noninvasive_15min.xlsx
    label: U
    time: 15
    replicates: 2
    sites: 5
    merge replicates: mean

  - file: data/WT_vs_noninvasive_1h.xlsx
    label: U
    time: 60
    replicates: 2
    sites: 5
    merge replicates: mean

  - file: data/WT_vs_noninvasive_2h.xlsx
    label: U
    time: 120
    replicates: 2
    sites: 5
    merge replicates: mean
    
PPI:
  BioGRID:
    experimental system:
      - Affinity Capture-Luminescence
      - Affinity Capture-MS
      - Affinity Capture-RNA 
      - Affinity Capture-Western
      - Biochemical Activity
      - Co-crystal Structure
      - Co-purification
      - FRET
      - PCA
      - Two-hybrid

  IntAct: 
    MI score: 0.27

  STRING:
    experiments: 0.7
    combined score: 0.7

Cytoscape:
  bar chart:
    minimum: -3.0
    maximum: 3.0
  mid range:
    minimum: -1.0
    maximum: 1.0
  merge sites: mean