BIOGRID = "https://downloads.thebiogrid.org/Download/BioGRID/Release-Archive/BIOGRID-4.2.191/BIOGRID-ALL-4.2.191.tab3.zip"
INTACT = "ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.zip"
UNIPROT_ID_MAP = "ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz"
STRING_ID_MAP = "https://string-db.org/mapping_files/uniprot/human.uniprot_2_string.2018.tsv.gz"
STRING = "https://stringdb-static.org/download/protein.links.full.v11.0/9606.protein.links.full.v11.0.txt.gz"
