on: 
  push:
    branches:
      - main
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - run: python3 -m pip install mypy
      - run: mypy --ignore-missing-imports ${{ GITHUB_WORKSPACE }}/diana/diana.py
