on:
  push:
    branches:
    - main
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
      - run: pip3 install mypy
      - run: mypy --ignore-missing-imports diana/diana.py
